// <auto-generated />
using System;
using Lex.Module.Scheduling.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Module.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    partial class SchedulingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("p_k_academic_years");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_academic_years_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_academic_years_name");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("i_x_academic_years_year");

                    b.ToTable("academic_years", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity")
                        .HasComment("Number of students the classroom can accommodate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Facilities")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("facilities")
                        .HasComment("Comma-separated list of facilities (e.g., Projector, Whiteboard)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_classrooms");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_classrooms_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_classrooms_name");

                    b.ToTable("classrooms", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes")
                        .HasComment("Optional notes (e.g., Lab session, Practical assessment)");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("teacher_id")
                        .HasComment("ID of the teacher assigned to teach this period (reference to identity system)");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("teacher_name")
                        .HasComment("Cached display name of the teacher for performance/readability");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_periods");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("i_x_periods_classroom_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_periods_is_active");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_periods_section_id");

                    b.HasIndex("Subject")
                        .HasDatabaseName("i_x_periods_subject");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("i_x_periods_teacher_id");

                    b.HasIndex("SlotId", "ClassroomId")
                        .IsUnique()
                        .HasDatabaseName("ix_unique_period_per_classroom_slot");

                    b.HasIndex("SlotId", "SectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_unique_period_per_section_slot");

                    b.HasIndex("SlotId", "TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ix_unique_period_per_teacher_slot");

                    b.ToTable("periods", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassTeacherId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("class_teacher_id")
                        .HasComment("ID or identifier of the class teacher/head teacher");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grade")
                        .HasComment("Academic level/grade (e.g., 9, 10, 11, 12)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("StudentCount")
                        .HasColumnType("integer")
                        .HasColumnName("student_count")
                        .HasComment("Estimated or actual student count in this section");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sections");

                    b.HasIndex("ClassTeacherId")
                        .HasDatabaseName("i_x_sections_class_teacher_id");

                    b.HasIndex("Grade")
                        .HasDatabaseName("i_x_sections_grade");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_sections_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_sections_name");

                    b.ToTable("sections", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week")
                        .HasComment("0=Sunday, 1=Monday, ..., 6=Saturday");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes")
                        .HasComment("Duration in minutes (e.g., 45 for 45-minute periods)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer")
                        .HasColumnName("slot_number")
                        .HasComment("Sequential slot number within the day (1, 2, 3, etc.)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_slots");

                    b.HasIndex("TermId", "SlotNumber")
                        .HasDatabaseName("i_x_slots_term_id_slot_number");

                    b.HasIndex("TermId", "DayOfWeek", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("ix_unique_slot_per_day_time");

                    b.ToTable("slots", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_terms");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_terms_is_active");

                    b.HasIndex("AcademicYearId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_terms_academic_year_id_sequence_number");

                    b.ToTable("terms", "scheduling");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Period", b =>
                {
                    b.HasOne("Lex.Module.Scheduling.Core.Domain.Classroom", "Classroom")
                        .WithMany("Periods")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_periods_classrooms_classroom_id");

                    b.HasOne("Lex.Module.Scheduling.Core.Domain.Section", "Section")
                        .WithMany("Periods")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_periods_sections_section_id");

                    b.HasOne("Lex.Module.Scheduling.Core.Domain.Slot", "Slot")
                        .WithMany("Periods")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_periods_slots_slot_id");

                    b.Navigation("Classroom");

                    b.Navigation("Section");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Slot", b =>
                {
                    b.HasOne("Lex.Module.Scheduling.Core.Domain.Term", "Term")
                        .WithMany("Slots")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_slots_terms_term_id");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Term", b =>
                {
                    b.HasOne("Lex.Module.Scheduling.Core.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Terms")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_terms_academic_years_academic_year_id");

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.AcademicYear", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Classroom", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Section", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Slot", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Lex.Module.Scheduling.Core.Domain.Term", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
