// <auto-generated />
using System;
using Lex.Module.DiaryManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Module.DiaryManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiaryDbContext))]
    [Migration("20260514154709_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diary")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Module.DiaryManagement.Core.Domain.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_diary_entries");

                    b.ToTable("diary_entries", "diary");
                });

            modelBuilder.Entity("Lex.Module.DiaryManagement.Core.Domain.DiaryEntry", b =>
                {
                    b.OwnsMany("Lex.Module.DiaryManagement.Core.Domain.DiaryAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("DiaryEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("diary_entry_id");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.HasKey("Id")
                                .HasName("p_k_diary_attachments");

                            b1.HasIndex("DiaryEntryId")
                                .HasDatabaseName("i_x_diary_attachments_diary_entry_id");

                            b1.ToTable("diary_attachments", "diary");

                            b1.WithOwner()
                                .HasForeignKey("DiaryEntryId")
                                .HasConstraintName("f_k_diary_attachments_diary_entries_diary_entry_id");
                        });

                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
