// <auto-generated />
using System;
using Lex.Module.AssessmentDelivery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Module.AssessmentDelivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssessmentDeliveryDbContext))]
    [Migration("20260514154301_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Module.AssessmentDelivery.Core.Domain.AssessmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sessions");

                    b.ToTable("sessions", "delivery");
                });

            modelBuilder.Entity("Lex.Module.AssessmentDelivery.Core.Domain.AssessmentSession", b =>
                {
                    b.OwnsMany("Lex.Module.AssessmentDelivery.Core.Domain.Answer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("content");

                            b1.Property<string>("QuestionId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("question_id");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("session_id");

                            b1.HasKey("Id")
                                .HasName("p_k_answers");

                            b1.HasIndex("SessionId")
                                .HasDatabaseName("i_x_answers_session_id");

                            b1.ToTable("answers", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("SessionId")
                                .HasConstraintName("f_k_answers_sessions_session_id");
                        });

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
