// <auto-generated />
using System;
using Lex.Module.LessonManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Module.LessonManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LessonDbContext))]
    [Migration("20260514154246_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lessons")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.ContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_content_block");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("i_x_content_block_lesson_id");

                    b.ToTable("content_block", "lessons");

                    b.HasDiscriminator<string>("Type").HasValue("ContentBlock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_lessons");

                    b.ToTable("lessons", "lessons");
                });

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.TextBlock", b =>
                {
                    b.HasBaseType("Lex.Module.LessonManagement.Core.Domain.ContentBlock");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.ToTable("content_block", "lessons");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.VideoBlock", b =>
                {
                    b.HasBaseType("Lex.Module.LessonManagement.Core.Domain.ContentBlock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.ToTable("content_block", "lessons");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.ContentBlock", b =>
                {
                    b.HasOne("Lex.Module.LessonManagement.Core.Domain.Lesson", null)
                        .WithMany("Blocks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_content_block_lessons_lesson_id");
                });

            modelBuilder.Entity("Lex.Module.LessonManagement.Core.Domain.Lesson", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
